development:
  adapter: postgresql
  encoding: UTF8
  database: project_development
  pool: 5
  host: 0.0.0.0

test:
  adapter: postgresql
  encoding: UTF8
  database: project_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: UTF8
  database: project_production
  pool: 5